- name: Deploy a web application
  hosts: db_and_web_server1, db_and_web_server2
  tasks:
    - name: Install all required dependencies
      apt: 
        name="{{ item }}" 
        state=present
      with_items:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python3-pip

    - name: Make sure pymysql is present
      become: true # needed if the other tasks are not played as root
      pip:
        name: pymysql
        state: present

    - name: Download MySQL Community Release package
      get_url:
        url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        dest: /tmp/mysql-community-release-el7-5.noarch.rpm

    - name: Install MySQL Community Release package
      apt:
        name: /tmp/mysql-community-release-el7-5.noarch.rpm
        state: present

    # - name: Install MySQL
    #   apt:
    #      name="{{ item }}"
    #      state=present
    #   with_items:
    #     - mysql-server
    #     - mysql-client

    - name: Start the MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create application database
      mysql_db: 
        name=employee_db
        state=present

    - name: Creat database user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Install python flask dependencies
      pip:
        name: "{{ item }}"
        state: present
      with_items:
       - flask
       - flask-mysql

    - name: Copy source code
      copy:
        src=app.py
        dest=/opt/app.py

    - name: Start web service
      shell: FLASK_APP=app.py nohup flask run --host=0.0.0.0 &
        
      
