- name: Install dependencies
  apt: 
      name: "{{ item }}" 
      state: present
  with_items:
    - python3
    - python-setuptools
    - python3-dev
    - build-essential
    - python3-pip
    - python3-mysqldb