-
  name: Test Jinja2 Templating
  hosts: localhost
  vars:
    first_name: Mohamed
    last_name: Abdel Aziz
  tasks:
  - debug:
      msg: 'The name is {{ last_name }}! {{ first_name }} {{ last_name }}!'