-
  name: Test Jinja2 Templating
  hosts: localhost
  gather_facts: no
  vars:
    first_name: Mohamed
    last_name: Abdel Aziz
    array_of_numbers:
      - 12
      - 34
      - 06
      - 34
  tasks:
  - debug:
      msg: 'The name is {{ last_name | title }}! {{ first_name | title }} {{ last_name | title }}!'

  # - shell: |
  #    echo 'Lowest = {{ array_of_numbers | min }}'
  - shell: echo 'Lowest = {{ array_of_numbers | min }}'
    register: print

  - debug: var=print.stdout_lines
