-
  name: Install Dependencies
  hosts: app_servers
  vars:
    web_dependencies:
         - python3
         - python-setuptools
         - python3-dev
         - build-essential
         - python3-pip
         - python3-mysqldb
    sql_dependencies:
         - python3
         - python3-mysqldb
  tasks:
  - name: Install dependencies
    apt: name='{{ item }}' state=installed
    with_items: '{{ web_dependencies | union(sql_dependencies) }}'
      