# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    (1..3).each do |i|
      config.vm.define "ubuntu#{i}" do |node|
        node.vm.box = "ubuntu/bionic64"
        node.vm.hostname = "ubuntu#{i}"
        node.vm.network "private_network", ip: "192.168.33.10#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
        end
      end
    end
  end  