-
  name: Deploy a web application
  hosts: db_and_web_server1, db_and_web_server2
  
  tasks:
    - name: Install dependencies
      apt: 
         name: "{{ item }}" 
         state: present
      with_items:
       - python3
       - python-setuptools
       - python3-dev
       - build-essential
       - python3-pip
       - python3-mysqldb

    - include_tasks: tasks/deploy_db.yml
    - include_tasks: tasks/deploy_web.yml

