VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Define the number of VMs (modify as needed)
  num_vms = 3

  # Loop to create multiple VMs
  (1..num_vms).each do |i|
    config.vm.define "ansible-client-#{i}" do |srv|

      # Set the desired Ubuntu version (check available boxes with `vagrant box list`)
      srv.vm.box = "ubuntu/focal64"

      # Configure private network with unique IPs for each VM
      srv.vm.network "private_network", ip: "200.100.100.#{10 + i}"

      # Configure vm hostname
      srv.vm.hostname = "ubuntu-client#{i}"

      # Provisioning with shell script (update commands as needed)
      srv.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y curl vim
      SHELL

      # Optional: Configure shared folders for easier access (modify paths)
      srv.vm.synced_folder ".", "/vagrant", type: "nfs"

      # Optional: Configure port forwarding (modify ports as needed)
      srv.vm.network "forwarded_port", guest: 80, host: 8080


      srv.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
        vb.memory = "512"
      end
    end
  end
end