VAGRANTFILE_API_VERSION = "2"

# require_relative '.vagrant/secrets.rb'
# include Secrets

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Define the number of VMs (modify as needed)
  num_vms = 2

  # Loop to create multiple VMs
  (1..num_vms).each do |i|
    config.vm.define "srv-#{i}" do |srv|

      # Set the desired Ubuntu version (check available boxes with `vagrant box list`)
      srv.vm.box = "bento/ubuntu-22.04"

      # Configure private network with unique IPs for each VM
      srv.vm.network "private_network", ip: "200.100.100.#{10 + i}"

      # Configure vm hostname
      srv.vm.hostname = "ubuntu-vm#{i}"

      # Provisioning with shell script (update commands as needed)
      srv.vm.provision "shell", inline: <<-SHELL
          # Creat ansible user
          sudo useradd -m -s /bin/bash -d /home/ansible ansible

          # Set password for user
          PASSWD="Passw0rd"
          USER="ansible"

          # Change user password
          echo -e "$PASSWD\n$PASSWD" | sudo passwd "$USER"

          # Optionally, ensure password change is successful
          if [ $? -eq 0 ]; then
              echo "Password for user $USER changed successfully."
          else
              echo "Failed to change password for user $USER."
          fi
      SHELL

      # Optional: Configure shared folders for easier access (modify paths)
      # srv.vm.synced_folder "./", "/vagrant", type: "nfs"

      # Optional: Configure port forwarding (modify ports as needed)
      # srv.vm.network "forwarded_port", guest: 80, host: 8090


      srv.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
        vb.memory = "1024"
      end
    end
  end
end