name: Build & Push Image

on:
    push:
        tags:
            '*'
        branches:
            - master

env:
    working-dir: 01-section

jobs:
    build-image:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-dir}}
        outputs:
            get-version: ${{ steps.get_version.outputs.VERSION }}
        steps:
            - uses: actions/checkout@v4
              with:
                path: ${{ env.working-dir }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: maziz00/ssh-srv:${{ steps.get_version.outputs.VERSION }}