name: Build & Push Image

on:
    push:
        tags:
            'v*.*'
    workflow_dispatch:

env:
    working-dir: 01-section

jobs:
    build-image:
        runs-on: ubuntu-latest
        outputs:
            get-version: ${{ steps.get_version.outputs.tag }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Get the version
              id: get_version
              run: |
                echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
                echo "$GITHUB_OUTPUT"

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: ${{ env.working-dir  }}
                push: true
                tags: maziz00/ssh-srv:${{ steps.get_version.outputs.tag }}